import 'package:nosso/src/core/model/arquivo.dart';
import 'package:nosso/src/core/model/cor.dart';

class Autogenerated {
  List<Content> content;
  Pageable pageable;
  int totalPages;
  int totalElements;
  bool last;
  bool first;
  int number;
  Sort sort;
  int numberOfElements;
  int size;
  bool empty;

  Autogenerated(
      {this.content,
        this.pageable,
        this.totalPages,
        this.totalElements,
        this.last,
        this.first,
        this.number,
        this.sort,
        this.numberOfElements,
        this.size,
        this.empty});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['content'] != null) {
      content = new List<Content>();
      json['content'].forEach((v) {
        content.add(new Content.fromJson(v));
      });
    }
    pageable = json['pageable'] != null
        ? new Pageable.fromJson(json['pageable'])
        : null;
    totalPages = json['totalPages'];
    totalElements = json['totalElements'];
    last = json['last'];
    first = json['first'];
    number = json['number'];
    sort = json['sort'] != null ? new Sort.fromJson(json['sort']) : null;
    numberOfElements = json['numberOfElements'];
    size = json['size'];
    empty = json['empty'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.content != null) {
      data['content'] = this.content.map((v) => v.toJson()).toList();
    }
    if (this.pageable != null) {
      data['pageable'] = this.pageable.toJson();
    }
    data['totalPages'] = this.totalPages;
    data['totalElements'] = this.totalElements;
    data['last'] = this.last;
    data['first'] = this.first;
    data['number'] = this.number;
    if (this.sort != null) {
      data['sort'] = this.sort.toJson();
    }
    data['numberOfElements'] = this.numberOfElements;
    data['size'] = this.size;
    data['empty'] = this.empty;
    return data;
  }
}

class Content {
  int id;
  String sku;
  String nome;
  String descricao;
  String foto;
  String dataRegistro;
  String codigoBarra;
  bool status;
  bool novo;
  bool destaque;
  String medida;
  String origem;
  SubCategoria subCategoria;
  Promocao promocao;
  Loja loja;
  List<Arquivo> arquivos;
  Estoque estoque;
  SubCategoria marca;
  List<Tamanhos> tamanhos;
  List<Cor> cores;
  int valorTotal;

  Content(
      {this.id,
        this.sku,
        this.nome,
        this.descricao,
        this.foto,
        this.dataRegistro,
        this.codigoBarra,
        this.status,
        this.novo,
        this.destaque,
        this.medida,
        this.origem,
        this.subCategoria,
        this.promocao,
        this.loja,
        this.arquivos,
        this.estoque,
        this.marca,
        this.tamanhos,
        this.cores,
        this.valorTotal});

  Content.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    sku = json['sku'];
    nome = json['nome'];
    descricao = json['descricao'];
    foto = json['foto'];
    dataRegistro = json['dataRegistro'];
    codigoBarra = json['codigoBarra'];
    status = json['status'];
    novo = json['novo'];
    destaque = json['destaque'];
    medida = json['medida'];
    origem = json['origem'];
    subCategoria = json['subCategoria'] != null
        ? new SubCategoria.fromJson(json['subCategoria'])
        : null;
    promocao = json['promocao'] != null
        ? new Promocao.fromJson(json['promocao'])
        : null;
    loja = json['loja'] != null ? new Loja.fromJson(json['loja']) : null;
    if (json['arquivos'] != null) {
      arquivos = new List<Arquivo>();
      json['arquivos'].forEach((v) {
        arquivos.add(new Arquivo.fromJson(v));
      });
    }
    estoque =
    json['estoque'] != null ? new Estoque.fromJson(json['estoque']) : null;
    marca =
    json['marca'] != null ? new SubCategoria.fromJson(json['marca']) : null;
    if (json['tamanhos'] != null) {
      tamanhos = new List<Tamanhos>();
      json['tamanhos'].forEach((v) {
        tamanhos.add(new Tamanhos.fromJson(v));
      });
    }
    if (json['cores'] != null) {
      cores = new List<Cor>();
      json['cores'].forEach((v) {
        cores.add(new Cor.fromJson(v));
      });
    }
    valorTotal = json['valorTotal'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['sku'] = this.sku;
    data['nome'] = this.nome;
    data['descricao'] = this.descricao;
    data['foto'] = this.foto;
    data['dataRegistro'] = this.dataRegistro;
    data['codigoBarra'] = this.codigoBarra;
    data['status'] = this.status;
    data['novo'] = this.novo;
    data['destaque'] = this.destaque;
    data['medida'] = this.medida;
    data['origem'] = this.origem;
    if (this.subCategoria != null) {
      data['subCategoria'] = this.subCategoria.toJson();
    }
    if (this.promocao != null) {
      data['promocao'] = this.promocao.toJson();
    }
    if (this.loja != null) {
      data['loja'] = this.loja.toJson();
    }
    if (this.arquivos != null) {
      data['arquivos'] = this.arquivos.map((v) => v.toJson()).toList();
    }
    if (this.estoque != null) {
      data['estoque'] = this.estoque.toJson();
    }
    if (this.marca != null) {
      data['marca'] = this.marca.toJson();
    }
    if (this.tamanhos != null) {
      data['tamanhos'] = this.tamanhos.map((v) => v.toJson()).toList();
    }
    if (this.cores != null) {
      data['cores'] = this.cores.map((v) => v.toJson()).toList();
    }
    data['valorTotal'] = this.valorTotal;
    return data;
  }
}

class SubCategoria {
  int id;
  String nome;

  SubCategoria({this.id, this.nome});

  SubCategoria.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    nome = json['nome'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['nome'] = this.nome;
    return data;
  }
}

class Promocao {
  int id;
  String nome;
  String descricao;
  String foto;
  int desconto;
  String dataRegistro;
  String dataInicio;
  String dataFinal;

  Promocao(
      {this.id,
        this.nome,
        this.descricao,
        this.foto,
        this.desconto,
        this.dataRegistro,
        this.dataInicio,
        this.dataFinal});

  Promocao.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    nome = json['nome'];
    descricao = json['descricao'];
    foto = json['foto'];
    desconto = json['desconto'];
    dataRegistro = json['dataRegistro'];
    dataInicio = json['dataInicio'];
    dataFinal = json['dataFinal'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['nome'] = this.nome;
    data['descricao'] = this.descricao;
    data['foto'] = this.foto;
    data['desconto'] = this.desconto;
    data['dataRegistro'] = this.dataRegistro;
    data['dataInicio'] = this.dataInicio;
    data['dataFinal'] = this.dataFinal;
    return data;
  }
}

class Loja {
  int id;
  String nome;
  String telefone;
  bool ativo;
  String tipoPessoa;
  String dataRegistro;
  String foto;
  String razaoSocial;
  String cnpj;

  Loja(
      {this.id,
        this.nome,
        this.telefone,
        this.ativo,
        this.tipoPessoa,
        this.dataRegistro,
        this.foto,
        this.razaoSocial,
        this.cnpj});

  Loja.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    nome = json['nome'];
    telefone = json['telefone'];
    ativo = json['ativo'];
    tipoPessoa = json['tipoPessoa'];
    dataRegistro = json['dataRegistro'];
    foto = json['foto'];
    razaoSocial = json['razaoSocial'];
    cnpj = json['cnpj'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['nome'] = this.nome;
    data['telefone'] = this.telefone;
    data['ativo'] = this.ativo;
    data['tipoPessoa'] = this.tipoPessoa;
    data['dataRegistro'] = this.dataRegistro;
    data['foto'] = this.foto;
    data['razaoSocial'] = this.razaoSocial;
    data['cnpj'] = this.cnpj;
    return data;
  }
}

class Estoque {
  int id;
  int quantidade;
  int valor;

  Estoque({this.id, this.quantidade, this.valor});

  Estoque.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    quantidade = json['quantidade'];
    valor = json['valor'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['quantidade'] = this.quantidade;
    data['valor'] = this.valor;
    return data;
  }
}

class Tamanhos {
  int id;
  String descricao;

  Tamanhos({this.id, this.descricao});

  Tamanhos.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    descricao = json['descricao'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['descricao'] = this.descricao;
    return data;
  }
}

class Pageable {
  Sort sort;
  int pageNumber;
  int pageSize;
  int offset;
  bool paged;
  bool unpaged;

  Pageable(
      {this.sort,
        this.pageNumber,
        this.pageSize,
        this.offset,
        this.paged,
        this.unpaged});

  Pageable.fromJson(Map<String, dynamic> json) {
    sort = json['sort'] != null ? new Sort.fromJson(json['sort']) : null;
    pageNumber = json['pageNumber'];
    pageSize = json['pageSize'];
    offset = json['offset'];
    paged = json['paged'];
    unpaged = json['unpaged'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.sort != null) {
      data['sort'] = this.sort.toJson();
    }
    data['pageNumber'] = this.pageNumber;
    data['pageSize'] = this.pageSize;
    data['offset'] = this.offset;
    data['paged'] = this.paged;
    data['unpaged'] = this.unpaged;
    return data;
  }
}

class Sort {
  bool sorted;
  bool unsorted;
  bool empty;

  Sort({this.sorted, this.unsorted, this.empty});

  Sort.fromJson(Map<String, dynamic> json) {
    sorted = json['sorted'];
    unsorted = json['unsorted'];
    empty = json['empty'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['sorted'] = this.sorted;
    data['unsorted'] = this.unsorted;
    data['empty'] = this.empty;
    return data;
  }
}